# custom tag that will be added to all saved df's and models. 
# useful if you are training say ggH classifier and want to save dataframe with ggH preselection. 
# otherwise may get confused when training another clf like VBF 
output_tag:
    'ggH_BDT'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        ggH:
            '2017': 'ggH_UL2017.root'
    bkg:
        DYMC:
            '2017': 'DY_UL2017.root'
        TT2L2Nu:
            '2017': 'TTLNu_UL2017.root'
        TTSemiL:
            '2017': 'TTSemi_UL2017.root'

data_file_names:
    Data:
        '2017': 'Data_UL2017.root'

#.root MC files for all years (bkg) should have these tree path:
proc_to_tree_name:
    ggH: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    TT2L2Nu: 'Events'
    TTSemiL: 'Events'

#X variables to train with. Must be in nominal_vars (unless created from existing features)
train_vars:
    ['leadElectronIDMVA', 'subleadElectronIDMVA', 'leadElectronPToM', 'subleadElectronPToM',
     'leadElectronEta', 'subleadElectronEta',
     'dielectronCosPhi', 'dielectronPt',
     'leadJetPt','subleadJetPt', 'leadJetPhi', 'subleadJetPhi',
     'dijetAbsDEta','dijetAbsDPhiTrunc', 'dijetCentrality', 'dijetMass']

#original ggH vars
#    ['leadElectronIDMVA', 'subleadElectronIDMVA', 'leadElectronPToM', 'subleadElectronPToM',
#     'leadElectronEta', 'subleadElectronEta',
#     'dielectronCosPhi', 'dielectronPt']

vars_to_add:
    leadElectronPToM:
    subleadElectronPToM:

#preselection that will be applied to all samples
preselection:
    'dielectronMass > 110 and dielectronMass < 150 and leadElectronPToM > 0.333 and subleadElectronPToM > 0.25'

#need looser cut to for re-weighting in 80 < m_ee < 100 GeV
reweight_cr:
    'dielectronMass > 80 and dielectronMass < 150 and leadElectronPToM > 0.333 and subleadElectronPToM > 0.25'
