# custom tag that will be added to all saved df's and models. 
signal_process:
    'ggH'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root MC files for all years (sig) should have this tree path:
mc_tree_name_sig:
    'vbfTagDumper/trees/ggh_125_13TeV_GeneralDipho'

#.root MC files for all years (bkg) should have this tree path:
mc_tree_name_bkg:
    'vbfTagDumper/trees/zee_13TeV_GeneralDipho'

mc_file_names:
    sig:
        '2017':
            'ggH_HToEE_2017.root'
    bkg:
        '2017':
            'DYMC_2017.root'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

#.root Data files for all years (data) should have this tree path:
data_tree_name:
    'vbfTagDumper/trees/Data_13TeV_GeneralDipho'

data_file_names:
    '2017':
        'DYData_2017_PAS5.root'

model_name:
    'ggH_vs_DYMC_clf'

#X variables to train with. Must be in nominal_vars (unless created from existing features)
train_vars:
    ['dipho_leadIDMVA', 'dipho_subleadIDMVA', 'dipho_lead_ptoM', 'dipho_sublead_ptoM',
     'dipho_leadEta', 'dipho_subleadEta',
      'CosPhi', 'vtxprob', 'sigmarv', 'sigmawv'] 

vars_to_add:
    

#preselection that will be applied to all samples
preselection:
    'dipho_mass > 110 and dipho_mass < 150 and dipho_leadIDMVA > -0.9 and dipho_subleadIDMVA > -0.9 and dipho_lead_ptoM > 0.333 and dipho_sublead_ptoM > 0.25 and dijet_Mjj<350'
