models:
    VBF: 'VBF_BDT_clf.pickle.dat'
    ggH: 'ggH_BDT_clf.pickle.dat'

boundaries:
    VBF: 
        tag_0: 0.884
        tag_1: 0.612
    ggH:
        tag_0: 0.751
        tag_1: 0.554
        tag_2: 0.331

