# custom tag that will be added to all saved df's and models. 
# useful if you are training say ggH classifier and want to save dataframe with ggH preselection. 
# otherwise may get confused when training another clf like VBF 
output_tag:
    'DY_validation_ggH_BDT'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        ggH:
            #'2016': 'ggH_UL2017.root' #re-use 2017 in 2016 for now
            '2017': 'ggH_UL2017.root'
            #'2018': 'ggH_UL2017.root' #re-use 2017 in 2018 for now
    bkg:
        DYMC:
            #'2016': 'DY_UL2016.root'
            '2017': 'DY_UL2017.root'
            #'2018': 'DY_UL2018.root'

data_file_names:
    Data:
        #'2016': 'Data_UL2016.root'
        '2017': 'Data_UL2017.root'
        #'2018': 'Data_UL2018.root'

#.root MC files for all years (bkg) should have these tree path:
proc_to_tree_name:
    ggH: 'Events'
    DYMC: 'Events'
    Data: 'Events'

#X variables to train with. Must be in nominal_vars (unless created from existing features)
train_vars:
#matching ggh_dnn vars
    ['dielectronPt','dielectronCosPhi',      
     'leadElectronPtOvM', 'subleadElectronPtOvM',
     'leadElectronEta', 'subleadElectronEta',
     'dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     'leadJetDieleDPhi', 'subleadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDEta',
     'leadJetEn', 'leadJetPt','leadJetEta', 'leadJetPhi','leadJetQGL', 
     'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL'
     ]
    

vars_to_add:

#preselection that will be applied to all samples. Here we want events in a ggH-like Z-mass control region 
preselection:
    'dielectronMass > 75 and dielectronMass < 105'

cut_map:
    dielectronMass: ['>80','<100']
    leadElectronPtOvM: ['>0.333']
    subleadElectronPtOvM: ['>0.25']
