# custom tag that will be added to all saved df's and models. 
output_tag:
    'VBF_DNN'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        VBF:
            '2017': 'VBF_UL2017.root'
            #'2017': 'VBF_HToEE_2017.root'
    bkg:
        DYMC:
            '2017': 'DY_UL2017.root'
        TT2L2Nu:
            '2017': 'TTLNu_UL2017.root'
        TTSemiL:
            '2017': 'TTSemi_UL2017.root'

data_file_names:
    Data:
        '2017': 'Data_UL2017.root'
        #'2018': 'DYData_2018_PAS5.root'

#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    VBF: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    TT2L2Nu: 'Events'
    TTSemiL: 'Events'

#X variables to train with (4 vectors of jets... and maybe photons... anything else that is low-level and maybe useful?)
object_vars:
    [['leadJetPt',  'leadJetEta', 'leadJetPhi','leadJetQGL'], #add lead jet en
     ['subleadJetPt',  'subleadJetEta', 'subleadJetPhi','subleadJetQGL'], #add sublead jet en
     ['subsubleadJetPt','subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL'] #add subsublead jet en
    ]

event_vars:
    ['leadElectronPToM', 'leadElectronIDMVA',
     'subleadElectronPToM', 'subleadElectronIDMVA',
     'dijetAbsDEta', 'dijetMass', 
     'dijetAbsDPhiTrunc', 'dijetCentrality'] #FIXME: dont have: dijet_dipho_dphi_trunc. see variables.py for more in

train_vars: #all vars for plotting inputs
    ['leadJetPt',  'leadJetEta', 'leadJetPhi','leadJetQGL',
     'subleadJetPt',  'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
     'subsubleadJetPt','subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL',
     'leadElectronPToM', 'leadElectronIDMVA',
     'subleadElectronPToM', 'subleadElectronIDMVA',
     'dijetAbsDEta', 'dijetMass', 
     'dijetAbsDPhiTrunc', 'dijetCentrality'] #FIXME: dont have: dijet_dipho_dphi_trunc. see variables.py for more in

vars_to_add:
    leadElectronPToM:
    subleadElectronPToM:

#preselection that will be applied to all samples
preselection:
    'dielectronMass > 110 and dielectronMass < 150 and leadElectronPToM > 0.333 and subleadElectronPToM > 0.25 and dijetMass>250 and leadJetPt>40 and subleadJetPt>30'
