# custom tag that will be added to all saved df's and models. 
output_tag:
    'ggH_DNN'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        ggH:
            '2017': 'ggH_UL2017.root'
    bkg:
        DYMC:
            '2017': 'DY_UL2017.root'
        TT2L2Nu:
            '2017': 'TTLNu_UL2017.root'
        TTSemiL:
            '2017': 'TTSemi_UL2017.root'

data_file_names:
    Data:
        '2017': 'Data_UL2017.root'
        #'2018': 'DYData_2018_PAS5.root'

#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    ggH: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    TT2L2Nu: 'Events'
    TTSemiL: 'Events'

#X variables to train with (4 vectors of jets... and maybe photons... anything else that is low-level and maybe useful?)
object_vars:
    [['leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL'], 
     ['subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL']
     #['subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi','subsubleadJetQGL']
    ]

event_vars:
    ['leadElectronPtOvM', 'subleadElectronPtOvM',
     'leadElectronEta', 'subleadElectronEta',
     'dielectronCosPhi', 'dielectronPt',
     'dijetMinDRJetEle', 'dijetDieleAbsDEta','dijetDieleAbsDPhiTrunc', 'dijetCentrality', 'dijetMass',
     'dijetAbsDEta', 'dijetAbsDPhi'] 

train_vars: #all vars for plotting inputs
    ['leadElectronPtOvM', 'subleadElectronPtOvM',
     'leadElectronEta', 'subleadElectronEta',
     'dielectronCosPhi', 'dielectronPt',
     'leadJetPt','subleadJetPt', 'leadJetPhi', 'subleadJetPhi', 
     'dijetMinDRJetEle', 'dijetDieleAbsDEta','dijetDieleAbsDPhiTrunc', 'dijetCentrality', 'dijetMass',
     'leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL', 
     'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
     'dijetAbsDEta', 'dijetAbsDPhi'] 
     #'subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL']
    
vars_to_add:
    leadElectronPToM:
    subleadElectronPToM:

#preselection that will be applied to all samples
preselection:
    'dielectronMass > 110 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25'

#need looser cut for re-weighting in 80 < m_ee < 100 GeV. Apply extra cut to get into CR later
reweight_cr:
    'dielectronMass > 80 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25'
