models:
    VBF: 'VBF_BDT_clf.pickle.dat'
    ggH: 'ggH_BDT_clf.pickle.dat'

boundaries:
    VBF: 
        tag_0: 0.869
        tag_1: 0.706
    ggH:
        tag_0: 0.777
        tag_1: 0.579
        tag_2: 0.312
