models:
    VBF: 'VBF_BDT_clf.pickle.dat'
    ggH: 'ggH_BDT_pt_reweighted_clf.pickle.dat'

boundaries:
    VBF: 
        tag_0: 0.899
        tag_1: 0.778
    ggH:
        tag_0: 0.769
        tag_1: 0.587
        tag_2: 0.276
