models:
    VBF: 'VBF_BDT_clf.pickle.dat'
    ggH: 'ggH_BDT_pt_reweighted_clf.pickle.dat'

boundaries:
    VBF: 
        tag_0: 0.911
        tag_1: 0.719
    ggH:
        tag_0: 0.849
        tag_1: 0.693
        tag_2: 0.510
        tag_3: 0.227
