models:
    VBF: 'VBF_BDT_clf.pickle.dat'
    ggH: 'ggH_BDT_pt_reweighted_clf.pickle.dat'

boundaries:
    VBF: 
        tag_0: 0.855
        tag_1: 0.616
    ggH:
        tag_0: 0.801
        tag_1: 0.591
        tag_2: 0.237
