models:
    VBF: 'VBF_BDT_clf.pickle.dat'
    ggH: 'ggH_BDT_pt_reweighted_clf.pickle.dat'

boundaries:
    VBF: 
        tag_0: 0.908 #lower mass
        tag_1: 0.753
    ggH:
        tag_0: 0.831
        tag_1: 0.717
        tag_2: 0.551
        tag_3: 0.267
